# Detect the drift from the upstream Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS drift
WORKDIR /app
COPY drift-cache/Dockerfile Dockerfile.cached
COPY Dockerfile .
# If the command below fails it means that the Dockerfile from this repository changed.
# You have to update the Konflux Containerfile accordingly.
# drift-cache/Dockerfile can be updated with the upstream contents once the Konflux version is aligned.
RUN test "$(sha1sum Dockerfile.cached | cut -d' ' -f1)" = "$(sha1sum Dockerfile | cut -d' ' -f1)"

FROM registry.access.redhat.com/ubi9/go-toolset:1.22.9-1744194661 as builder
# dummy copy to trigger the drift detection
COPY --from=drift /app/Dockerfile.cached .

WORKDIR /workspace
# Dummy RUN to create /workspace directory.
# WORKDIR doesn't create the directory (at least for Podman).
# Without this step, the following COPY may create /workspace
# as root-owned (instead of go-toolset's default 1001)
# leading to "Permission denied" errors during "go build"
# when trying to write output.
RUN ls .
COPY . /workspace

# Build
RUN GOOS=linux GOARCH=amd64 go build -tags strictfipsruntime -a -o manager main.go

FROM registry.access.redhat.com/ubi9/ubi:9.6-1751287003
LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="aws-load-balancer-operator-container"
LABEL name="aws-load-balancer-operator"
LABEL version="1.2.0"
WORKDIR /
COPY --from=builder /workspace/manager /
USER 65532:65532
COPY LICENSE /licenses/
ENTRYPOINT ["/manager"]
