# Detect the drift from the upstream Dockerfile
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest AS drift
WORKDIR /app
COPY drift-cache/Dockerfile Dockerfile.cached
COPY Dockerfile .
# If the command below fails it means that the Dockerfile from this repository changed.
# You have to update the Konflux Containerfile accordingly.
# drift-cache/Dockerfile can be updated with the upstream contents once the Konflux version is aligned.
RUN test "$(sha1sum Dockerfile.cached | cut -d' ' -f1)" = "$(sha1sum Dockerfile | cut -d' ' -f1)"

FROM registry.access.redhat.com/ubi8/go-toolset:1.25 as builder
# dummy copy to trigger the drift detection
COPY --from=drift /app/Dockerfile.cached .
WORKDIR /workspace
# Dummy RUN to create /workspace directory.
# WORKDIR doesn't create the directory (at least for Podman).
# Without this step, the following COPY may create /workspace
# as root-owned (instead of go-toolset's default 1001)
# leading to "Permission denied" errors during "go build"
# when trying to write output.
RUN ls .
COPY . /workspace
# Build
RUN GOOS=linux GOARCH=amd64 go build -tags strictfipsruntime -a -o manager main.go

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest@sha256:fed79bafb51b25e53c902756ae4f9c0925453d56c9fb5b142505b5af8b554f35
# Define build arguments to receive dynamic values
ARG FULL_COMMIT
ARG GIT_URL
LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="aws-load-balancer-operator-container"
LABEL name="albo/aws-load-balancer-rhel8-operator"
LABEL version="1.2.1"
LABEL cpe="cpe:/a:redhat:aws_lb_optr:1.2::el8"
LABEL io.openshift.build.commit.id=${FULL_COMMIT}
LABEL io.openshift.build.source-location=${GIT_URL}
LABEL io.openshift.build.commit.url=${GIT_URL}/commit/${FULL_COMMIT}
WORKDIR /
COPY --from=builder /workspace/manager /
USER 65532:65532
COPY LICENSE /licenses/
ENTRYPOINT ["/manager"]
