# Detect the drift from the upstream Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS drift
WORKDIR /app
COPY drift-cache/catalog.Dockerfile Dockerfile.cached
COPY catalog.Dockerfile .
# If the command below fails it means that the catalog.Dockerfile from this repository changed.
# You have to update the Konflux Containerfile accordingly.
# drift-cache/catalog.Dockerfile can be updated with the upstream contents once the Konflux version is aligned.
RUN test "$(sha1sum Dockerfile.cached | cut -d' ' -f1)" = "$(sha1sum catalog.Dockerfile | cut -d' ' -f1)"

# The base image is expected to contain
# /bin/opm (with a serve subcommand) and /bin/grpc_health_probe
FROM registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.19
# dummy copy to trigger the drift detection
COPY --from=drift /app/catalog.Dockerfile .

# Configure the entrypoint and command
ENTRYPOINT ["/bin/opm"]
# Copy the ALBO FBC catalog
COPY catalog/aws-lb-optr-1-3 /configs/aws-load-balancer-operator

# Pre-populate serve cache
RUN ["/bin/opm", "serve", "/configs/aws-load-balancer-operator", "--cache-dir=/tmp/cache", "--cache-only"]

# Set DC-specific label for the location of the DC root directory
# in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs/aws-load-balancer-operator

# Configure the command to serve the catalog
CMD ["serve", "/configs/aws-load-balancer-operator", "--cache-dir=/tmp/cache"]
