apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: aws-load-balancer-operator-metrics-scraper
  name: aws-load-balancer-operator-metrics-scraper-token
type: kubernetes.io/service-account-token
