# permissions for end users to view awsloadbalancercontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsloadbalancercontroller-viewer-role
rules:
- apiGroups:
  - networking.olm.openshift.io
  resources:
  - awsloadbalancercontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.olm.openshift.io
  resources:
  - awsloadbalancercontrollers/status
  verbs:
  - get
