# permissions for end users to edit awsloadbalancercontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsloadbalancercontroller-editor-role
rules:
- apiGroups:
  - networking.olm.openshift.io
  resources:
  - awsloadbalancercontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.olm.openshift.io
  resources:
  - awsloadbalancercontrollers/status
  verbs:
  - get
