apiVersion: v1
kind: Secret
metadata:
  name: metrics-scraper-token
  namespace: system
  annotations:
    kubernetes.io/service-account.name: aws-load-balancer-operator-metrics-scraper
type: kubernetes.io/service-account-token
