apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: aws-load-balancer-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AWSLoadBalancerController is the Schema for the awsloadbalancercontrollers
        API
      displayName: AWSLoad Balancer Controller
      kind: AWSLoadBalancerController
      name: awsloadbalancercontrollers.networking.olm.openshift.io
      version: v1alpha1
  description: Operator to simplify management of aws-load-balancer-controller
  displayName: aws-load-balancer-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aws
  - load-balancer
  - ALB
  - ingress
  links:
  - name: Aws Load Balancer Operator
    url: https://aws-load-balancer-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
    url: https://redhat.com
  version: 0.0.0
