apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: aws-load-balancer-controller
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - acm:DescribeCertificate
      - acm:ListCertificates
      - cognito-idp:DescribeUserPoolClient
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:CreateSecurityGroup
      - ec2:CreateTags
      - ec2:DeleteSecurityGroup
      - ec2:DeleteTags
      - ec2:Describe*
      - ec2:GetCoipPoolUsage
      - ec2:RevokeSecurityGroupIngress
      - elasticloadbalancing:AddListenerCertificates
      - elasticloadbalancing:AddTags
      - elasticloadbalancing:CreateListener
      - elasticloadbalancing:CreateLoadBalancer
      - elasticloadbalancing:CreateRule
      - elasticloadbalancing:CreateTargetGroup
      - elasticloadbalancing:DeleteListener
      - elasticloadbalancing:DeleteLoadBalancer
      - elasticloadbalancing:DeleteRule
      - elasticloadbalancing:DeleteTargetGroup
      - elasticloadbalancing:DeregisterTargets
      - elasticloadbalancing:Describe*
      - elasticloadbalancing:ModifyListener
      - elasticloadbalancing:ModifyLoadBalancerAttributes
      - elasticloadbalancing:ModifyRule
      - elasticloadbalancing:ModifyTargetGroup
      - elasticloadbalancing:ModifyTargetGroupAttributes
      - elasticloadbalancing:RegisterTargets
      - elasticloadbalancing:RemoveListenerCertificates
      - elasticloadbalancing:RemoveTags
      - elasticloadbalancing:SetIpAddressType
      - elasticloadbalancing:SetSecurityGroups
      - elasticloadbalancing:SetSubnets
      - elasticloadbalancing:SetWebAcl
      - iam:CreateServiceLinkedRole
      - iam:GetServerCertificate
      - iam:ListServerCertificates
      - shield:CreateProtection
      - shield:DeleteProtection
      - shield:DescribeProtection
      - shield:GetSubscriptionState
      - waf-regional:AssociateWebACL
      - waf-regional:DisassociateWebACL
      - waf-regional:GetWebACL
      - waf-regional:GetWebACLForResource
      - wafv2:AssociateWebACL
      - wafv2:DisassociateWebACL
      - wafv2:GetWebACL
      - wafv2:GetWebACLForResource
      effect: Allow
      resource: "*"
  secretRef:
    name: aws-load-balancer-controller-manual-cluster
    namespace: aws-load-balancer-operator
  serviceAccountNames:
  - aws-load-balancer-controller-cluster
